### ISSUE TITLE
Add your favourite bible verses

### ISSUE THREAD

**Issue by damcclean** [BiblioSpot/Hacktoberfest#1]
Feel free to add your favourite bible verse(s) to the readme.md file in this repository.

Anyone can add verses! Although, please remember to [format everything correctly](https://github.com/BiblioSpot/Hacktoberfest/#template).

**Comment by CyjKun** [comment]
can i work on this issue?

**Comment by damcclean** [comment]
Yeah, anyone can work on this issue!

**Comment by Anyitechs** [comment]
@damcclean can i still make a pull request, and contribute on this issue?

**Comment by damcclean** [comment]
Yeah @Anyitechs! Feel free to contribute!

**Comment by damcclean** [comment]
Hacktoberfest 2018 is over :( sad times. We'll be back next year!
